<?php

use Drupal\commerce_order\Entity\OrderInterface;
use Drupal\commerce_product\Entity\ProductVariationInterface;
use Drupal\file\Entity\File;

/**
 * Implements hook_preprocess_HOOK() for commerce_order_receipt.
 */
function custom_pdf_attachment_preprocess_commerce_order_receipt(array &$variables) {
  if (empty($variables['order_entity']) || !$variables['order_entity'] instanceof OrderInterface) {
    return;
  }

  $order = $variables['order_entity'];
  $download_links = [];

  $file_url_generator = \Drupal::service('file_url_generator');

  foreach ($order->getItems() as $order_item) {
    /** @var ProductVariationInterface $variation */
    $variation = $order_item->getPurchasedEntity();
    if ($variation && $variation->hasField('commerce_file')) {
      foreach ($variation->get('commerce_file') as $field_item) {
        $file = $field_item->entity;
        if ($file instanceof File) {
          $url = $file_url_generator->generateAbsoluteString($file->getFileUri());
          $download_links[] = [
            'title' => $file->getFilename(),
            'url' => $url,
          ];
        }
      }
    }
  }

  $variables['download_links'] = $download_links;
}
