<?php
use Drupal\Core\Database\Database;
use Drupal\node\Entity\Node;

$webform_urls = [
  'kulturpris',
  'anmeldelse-af-ansvarsskadesag',
  'seniorbofaellesskab-i-ballerup-kommune',
  'ansoegning-kunstgraesbaner-hverdage',
  'mikrofrivillig',
  'ansoegning-om-uddannelsestilskud',
  'skema-til-projekt-ide',
  'oplysningsskema-om-frivilligt-arbejde-i-ballerup-kommune',
  'talentpris',
  'ansoegning-om-tilskud-til-frivilligt-socialt-arbejde-i-ballerup-kommune-ss-18-i-lov-om-social',
  'skema-til-booking-af-lokale',
  'ansoegning-om-dagtilbud-i-traening-aktivitet-ballerup-kommune',
  'ansoegning-kunstgraesbane-weekend',
  'ansoegning-om-traening-i-traening-og-aktivitet-ballerup-kommune',
  'aarets-leder',
  'sundhedspris-boern-og-unge',
  'ballerup-kommunes-sundhedspris',
  'soeg-social-og-sundhedshjaelper-uddannelsen',
  'node/48900',
  'fortrolighedserklaering-eksterne-leverandoermedarbejdere',
  'boligansoegningsformular',
  'fortrolighedserklaering-eksterne-medarbejdere',
  'databehandleraftale',
  'indhold/forslag-om-besparelse-til-budget-2018',
  'borgermoede2',
  'borger/born-unge/anmodning-om-skolekort-til-elever-i-specialtilbud',
  'borger/born-unge/anmodning-om-duplikatkort-til-elever-i-specialtilbud',
  'indhold/quiz-hvad-ved-du-om-andre-unge',
  'indhold/quiz-hvad-ved-du-om-andre-unge-0',
  'feedback',
  'borgermoede',
  'borgermillionskema',
  'ansoegning-om-mentorprogram',
  'indhold/webform-default-fields-master-node',
  'test-vejledning-i-os2forms',
  'om-kommunen/politik/tilmelding-til-infomoede-om-pleje-og-aflastningsfamilier',
  'ansoegning-om-parkeringstilladelse',
  'c-bem-ledelsens-evaluering',
  'seniorbofaellesskab-boligansoegning',
  'anmodning-om-adgang-til-opendesk',
  'erklaering-om-brug-af-kommunens-mobiltelefon',
  'borger/sundhed-pleje/tilbud-til-voksne-med-saerlige-behov/botilbud/ansoegning-om-tildeling-af-plads',
  'skoler/tilmelding',
  'anmeldelse-af-ansvarsskadesag-0',
  'spoergeskema-foer-afproevning-af-kaede-eller-kugledyne-barn',
  'boligansoegning-ballerup-kommune',
  'den-gode-overgang-spoergeskema-til-foraeldre',
  'genbevilling-af-hjaelpemiddel-forbrugsgodeboligindretning-serviceloven-ssss-112113116',
  'adgang-eksterne-samarbejdspartnere',
  'test-pdf',
  'indsigt',
  'databehandleraftale-0',
  'skabelon-borger-nemid',
  'skabelon-borger-virksomhed-nemid',
  'borger/born-unge/skoler/folkeskole/elementer-i-skoler/tilladelse-til-brug-af-billeder',
  'adgangstilladelse-til-centrumgaden',
  'test-4',
  'spoergeskema-foer-afproevning-af-kaede-eller-kugledyne-voksen',
  'spoergeskema-under-afproevning-af-kaede-eller-kugledyne-voksen',
  'spoergeskema-under-afproevning-af-kaede-eller-kugledyne-barn',
  'visum-til-kina',
  'book-en-politiker',
  'book-en-lokalpolitiker',
  'formular-test-skal-bare-slettes',
  'ansoegning-om-kropsbaarne-hjaelpemidler',
  'sikkerbesked',
  'test-nemlogin',
  'test-nemid-blok',
  'samtykkeerklaering-til-brug-af-foto-eller-video',
  'samtykkeerklaering-vedroerende-anvendelse-af-billeder-og-film-skoler-og-bfo',
  'tilbagetraekning-af-foto-og-videosamtykke',
  'ansoegning-om-adgang-til-privat-faellesvej',
  'ansoegning-om-adgang-til-offentlig-vej',
  'samtykke-videregivelse-af-tjenestetidsoplysninger',
  'test-alt-leif',
  'referenceskema',
  'oplysning-om-behov-pasning-ved-lukkedage',
  'sikker-besked-til-borgerraadgiver',
  'tilmelding-til-familieplejens-nyhedsbrev',
  'tilmelding-som-valgtilforordnet-i-forbindelse-med-det-kommende-folketingsvalg',
  'tilmelding-som-valgtilforordnet-til-europaparlamentsvalget-soendag-den-26-maj-2019',
  'grundliste',
  'regnskabsaflaeggelse-tilskud-til-aktiviteter',
  'ansoegning-om-aktivitetstilskud',
  'indmeldelse-i-klub',
  'test-erklaering-om-oplysningspligt',
  'tilskud-til-tandpleje-tilmelding',
  'refusion-i-forbindelse-med-udgifter-til-helbredstillaeg-fx-tandbehandling-og-fodbehandling',
  'ret-og-pligt-ved-kontanthjaelp',
  'ret-og-pligt-ved-uddannelseshjaelp',
  'erklaering-om-oplysningspligt',
  'skolestart-information-fra-foraeldre-til-bfoskole',
  'visum-til-kina-skoleelever',
  'ansoegning-om-et-socialt-frikort',
  'samtykkeerklaering-vedroerende-anvendelse-af-billeder-af-dit-barn',
  'sikker-besked-til-databeskyttelsesraadgiver',
  '6-ferieuge-blanketten-er-ikke-i-brug-mere',
  'ansoegning-om-parkeringstilladelse-lundehaven',
  'indstilling-af-virksomhed-til-virksomhedspris',
  'ansoegning-om-tid-i-idraetslokaler-efter-halfordelingen',
  'integrationsprisen',
  'barselsorlov-skema-2',
  'grundlovsceremoni',
  'fordeling-af-haller-i-weekender',
  'fordeling-af-gymnastik-kondi-barfodsale',
  'fordeling-af-svoemmesale',
  'fordeling-af-haller-i-hverdage',
  'ansoegning-om-idraetsfaciliteter-til-projekter',
  'barsel-indsend-vandrejournal',
  'test-barselskema-2',
  'tillaeg-til-uddannelsesaftalen',
  'allonge-til-uddannelsesaftalen',
  'allonge-hjemmeplejen',
  'borgerforslag-formular',
  'arkiv/c-bem/testformularplacering',
  'jubilaeum-paa-raadhuset',
  'jubilaeum-uden-raadhuset',
  'den-gode-overgang-og-opstart-i-boernehus-dagpleje',
  'udskudt-foraeldreorlov',
  'aktivitetsskema',
  'aktivitetsskema-skyggeformular',
  'referenceskema-ved-uddannelse',
  'afskedsreception-paa-raadhuset',
  'jubilaeum-paa-raadhuset-test',
  'afskedsreception-uden-raadhuset',
  'visum-til-kina-forening-klub',
  'udlaan-af-ipad-til-medlemmer-af-raad-og-naevn',
  'vi-har-brug-dig',
  'laaner-under-18-aar-paa-ballerup-kommunes-biblioteker',
  'vi-har-brug-dig-intern',
  '6-ferieuge-fristen-ansoegning-er-udloebet',
  'samtykke-til-indhentning-af-straffe-og-boerneattester-intern',
  'samtykke-til-indhentning-af-straffe-og-boerneattester-og-dokumentation',
  'borgerforslag-forslag-titel',
  'borgerforslag-flere-el-bil-laderstandere-i-ballerup',
  'aftale-om-frivillig-indsats-paa-ballerup-bibliotekerne',
  'borgerforslag-groen-guide-i-ballerup-kommune',
  'borgerforslag-torv-i-lokalplan-skovlunde-center-syd',
  '6-ferieuge-annullering-af-ansoegning',
  'fordeling-af-kunstgraesbaner',
  'borgerforslag-forbud-mod-braendeovne',
  'delvis-refusion-af-flextur-koersel-ved-vaengerne-sommer-2020',
  'borgerforslag-springvand-i-soendergaard-soe',
  'borgerforslag-tilskud-til-pasning-af-eget-barn',
  'ferie-paa-forskud-ansoegning',
  'frivillig-ung',
  'besked',
  'webtilgaengelighed',
  'indberetning-af-udlaeg',
  'borgerforslag-fremtids-investering-i-gode-trafikanter',
  'fordeling-af-haller-i-hverdag',
  'ansoegning-om-uddannelsestilskud-0',
  'anmeldelser-om-kolonihaver',
  'ansoegning-om-militaerpraktik',
  'samtykkeerklaering-arbejdsmarked-prototype',
  'nyansat-med-feriekort-fra-tidligere-arbejdsgiver',
  'test-referenceskema-og-andre-oplysninger',
  'borgerforslag-omdannelse-af-jonstruplejren',
  'ansoegning-til-seniorjob',
];

$storage = \Drupal::entityTypeManager()->getStorage('redirect');

$redirect_base_url = 'http://formular.ballerup.dk';
$added = 0;
$skipped = 0;
$repository = \Drupal::service('redirect.repository');

foreach ($webform_urls as $url) {
  $existing = $repository->findBySourcePath($url);
  if (!empty($existing)) {
    print_r('Redirect for URL ' . $url . ' already exists.' . PHP_EOL);
    $skipped++;
    continue;
  }

  /** @var \Drupal\redirect\Entity\Redirect $redirect */
  $redirect = $storage->create();
  $redirect->setSource($url);
  $redirect->setRedirect($redirect_base_url . '/' . $url);
  $redirect->setStatusCode(301);
  $redirect->save();
  print_r('Added redirect for URL ' . $url . PHP_EOL);
  $added++;
}
print_r(sprintf('Webforms redirects adding finished: total: %d, added %d, skipped %d', count($webform_urls), $added, $skipped) . PHP_EOL);



